spring:
  redis:
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    database: 0  # Redis数据库索引（默认为0）
    timeout: 6000
    lettuce:
      pool:
        max-active: 20 #连接池最大连接数（使用负值表示没有限制）
        pool.max-wait: 3000 #连接池最大阻塞等待时间（使用负值表示没有限制）
        pool.max-idle: 10 #连接池中的最大空闲连接
        pool.min-idle: 5 #连接池中的最小空闲连接

snowflake:
  datacenterId: 2
  workerId: ${random.int[1,31]}